# This is a basic workflow to help you get started with Actions

name: Build GUI exe with PyInstaller
on:
  push:
    branches: [ dev ]
  pull_request: [ master ]

jobs:
  release-project: 
    name: Release Executable
    runs-on: ubuntu-latest
    needs: build-project 

    steps:
      - uses: actions/download-artifact@v2

      - name: Create Archive
        uses: thedoctor0/zip-release@master
        with:
          filename: 'tofu_video_labeller.zip'
      
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tofu_video_labeller.zip"
          tag: v0.${{ github.run_number }}
          name: Release V0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-project:
    name: Build Executable for Windows OS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: tofu_video_labeller_exe
          path: src/dist/windows
  